### ISSUE TITLE
protecting the service against undesired usage

### ISSUE THREAD

**Issue by esakal** [omercnet/israeli-bank-scrapers-api#2]
Hi,
Pretty cool 👍 

Have you considered adding a protection (either with environment master password/token or with more robust authentication mechanism) so anonymous people will not be able to trigger scrapping?

**Comment by omercnet** [comment]
Hi! thanks for the feedback :)

this is not meant to be used as a public service, the goal is for this to be an internal microservice within a larger application
if you'd like to add authentication in front of it consider using something like https://github.com/omercnet/docker-nginx-basic-auth

**Comment by esakal** [comment]
Ah! make sense :) thanks
